# Generated by Django 3.2.6 on 2021-08-17 17:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.TextField(verbose_name='Note'),
        ),
    ]
