# Generated by Django 3.2.6 on 2021-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210817_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='customer@mail.com', max_length=250, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
