# Generated by Django 3.2.6 on 2021-08-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210817_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default='John Doe', max_length=250, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
